```{r data generation, echo = FALSE, results = "hide"}
#possible.repo <- getCRANmirrors()$URL  # doenst work well for all repos

possible.repo <- c('https://cloud.r-project.org/',
                  'http://mirror.fcaglp.unlp.edu.ar/CRAN/',
                  'http://cran-r.c3sl.ufpr.br/',
                  'http://cran.stat.sfu.ca/',
                  'https://mirrors.dotsrc.org/cran/',
                  'https://mirrors.cicku.me/CRAN/',
                  'https://cran.ism.ac.jp/')

my.repo <- sample(possible.repo,1)

n.pkgs <- nrow(available.packages(repos = my.repo))

sol.q <- n.pkgs
rnd.vec <- c(0, sample(-5000:-1,4))

my.answers <- paste0(sol.q+rnd.vec, ' packages')
```

Question
========

How many packages you can find today (`r Sys.Date()`) in CRAN? 

Use repository `r my.repo` for the solution.

```{r questionlist, echo = FALSE, results = "asis"}
answerlist(my.answers, markup = "markdown")
```

Meta-information
================
extype: schoice
exsolution: 10000
exname: numbero of cran pkgs
exshuffle: TRUE
